# Generated by Django 3.2.7 on 2022-03-25 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('name', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('region_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_App.region')),
            ],
        ),
    ]
