# Generated by Django 3.2.7 on 2022-05-04 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0002_analysis_parameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='time',
            field=models.DateTimeField(default=datetime.date(2022, 5, 4)),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2147483647, unique=True)),
                ('is_easy', models.BooleanField(default=True)),
                ('is_access_to_current_block', models.BooleanField(default=False)),
                ('is_access_to_other_block', models.BooleanField(default=False)),
                ('unlocked_block_code', models.IntegerField(default=None, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_App.block')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main_App.question')),
            ],
        ),
    ]
