# Generated by Django 3.2.7 on 2022-05-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0003_auto_20220504_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block', to='Main_App.block'),
        ),
        migrations.AlterField(
            model_name='question',
            name='unlocked_block_code',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_block', to='Main_App.block'),
        ),
    ]
