# Generated by Django 3.2.7 on 2022-05-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0004_auto_20220504_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_access_to_current_block',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_access_to_other_block',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_easy',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TE', 'Easy'), ('TUCB', 'Unlock current block'), ('TUOB', 'Unlock other block')], default='TE', max_length=4),
        ),
    ]
