# Generated by Django 3.2.7 on 2022-05-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main_App', '0005_auto_20220504_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='unlocked_block_code',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unlocked_block', to='Main_App.block'),
        ),
    ]
